/**
 * @fileoverview gRPC-Web generated client stub for pb
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.1
// source: proto/auth.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_base_pb from '../proto/base_pb'; // proto import: "proto/base.proto"
import * as proto_auth_pb from '../proto/auth_pb'; // proto import: "proto/auth.proto"
import * as proto_user_pb from '../proto/user_pb'; // proto import: "proto/user.proto"


export class AuthServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorLogin = new grpcWeb.MethodDescriptor(
    '/pb.AuthService/Login',
    grpcWeb.MethodType.UNARY,
    proto_auth_pb.LoginRequest,
    proto_auth_pb.LoginResponse,
    (request: proto_auth_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    proto_auth_pb.LoginResponse.deserializeBinary
  );

  login(
    request: proto_auth_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_auth_pb.LoginResponse>;

  login(
    request: proto_auth_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_auth_pb.LoginResponse) => void): grpcWeb.ClientReadableStream<proto_auth_pb.LoginResponse>;

  login(
    request: proto_auth_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_auth_pb.LoginResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.AuthService/Login',
        request,
        metadata || {},
        this.methodDescriptorLogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.AuthService/Login',
    request,
    metadata || {},
    this.methodDescriptorLogin);
  }

  methodDescriptorLogout = new grpcWeb.MethodDescriptor(
    '/pb.AuthService/Logout',
    grpcWeb.MethodType.UNARY,
    proto_base_pb.Empty,
    proto_base_pb.Empty,
    (request: proto_base_pb.Empty) => {
      return request.serializeBinary();
    },
    proto_base_pb.Empty.deserializeBinary
  );

  logout(
    request: proto_base_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<proto_base_pb.Empty>;

  logout(
    request: proto_base_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_base_pb.Empty) => void): grpcWeb.ClientReadableStream<proto_base_pb.Empty>;

  logout(
    request: proto_base_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_base_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.AuthService/Logout',
        request,
        metadata || {},
        this.methodDescriptorLogout,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.AuthService/Logout',
    request,
    metadata || {},
    this.methodDescriptorLogout);
  }

  methodDescriptorInfo = new grpcWeb.MethodDescriptor(
    '/pb.AuthService/Info',
    grpcWeb.MethodType.UNARY,
    proto_base_pb.Empty,
    proto_user_pb.User,
    (request: proto_base_pb.Empty) => {
      return request.serializeBinary();
    },
    proto_user_pb.User.deserializeBinary
  );

  info(
    request: proto_base_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<proto_user_pb.User>;

  info(
    request: proto_base_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_user_pb.User) => void): grpcWeb.ClientReadableStream<proto_user_pb.User>;

  info(
    request: proto_base_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_user_pb.User) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.AuthService/Info',
        request,
        metadata || {},
        this.methodDescriptorInfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.AuthService/Info',
    request,
    metadata || {},
    this.methodDescriptorInfo);
  }

  methodDescriptorRefreshToken = new grpcWeb.MethodDescriptor(
    '/pb.AuthService/RefreshToken',
    grpcWeb.MethodType.UNARY,
    proto_base_pb.Empty,
    proto_auth_pb.RefreshTokenResponse,
    (request: proto_base_pb.Empty) => {
      return request.serializeBinary();
    },
    proto_auth_pb.RefreshTokenResponse.deserializeBinary
  );

  refreshToken(
    request: proto_base_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<proto_auth_pb.RefreshTokenResponse>;

  refreshToken(
    request: proto_base_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_auth_pb.RefreshTokenResponse) => void): grpcWeb.ClientReadableStream<proto_auth_pb.RefreshTokenResponse>;

  refreshToken(
    request: proto_base_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_auth_pb.RefreshTokenResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.AuthService/RefreshToken',
        request,
        metadata || {},
        this.methodDescriptorRefreshToken,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.AuthService/RefreshToken',
    request,
    metadata || {},
    this.methodDescriptorRefreshToken);
  }

}

