/**
 * @fileoverview gRPC-Web generated client stub for pb
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.1
// source: proto/file.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_file_pb from '../proto/file_pb'; // proto import: "proto/file.proto"


export class FileServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorInfo = new grpcWeb.MethodDescriptor(
    '/pb.FileService/Info',
    grpcWeb.MethodType.UNARY,
    proto_file_pb.FileInfoRequest,
    proto_file_pb.FileInfo,
    (request: proto_file_pb.FileInfoRequest) => {
      return request.serializeBinary();
    },
    proto_file_pb.FileInfo.deserializeBinary
  );

  info(
    request: proto_file_pb.FileInfoRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_file_pb.FileInfo>;

  info(
    request: proto_file_pb.FileInfoRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_file_pb.FileInfo) => void): grpcWeb.ClientReadableStream<proto_file_pb.FileInfo>;

  info(
    request: proto_file_pb.FileInfoRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_file_pb.FileInfo) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.FileService/Info',
        request,
        metadata || {},
        this.methodDescriptorInfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.FileService/Info',
    request,
    metadata || {},
    this.methodDescriptorInfo);
  }

  methodDescriptorDownload = new grpcWeb.MethodDescriptor(
    '/pb.FileService/Download',
    grpcWeb.MethodType.SERVER_STREAMING,
    proto_file_pb.DownloadFileRequest,
    proto_file_pb.Chunk,
    (request: proto_file_pb.DownloadFileRequest) => {
      return request.serializeBinary();
    },
    proto_file_pb.Chunk.deserializeBinary
  );

  download(
    request: proto_file_pb.DownloadFileRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<proto_file_pb.Chunk> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/pb.FileService/Download',
      request,
      metadata || {},
      this.methodDescriptorDownload);
  }

}

